[package]
name = "AutoNudge"
namespace = "doombubbles"
description = "When placing a tower, you can press the Auto Nudge hotkey (default Tab) to automatically move your mouse / the tower to the closest valid spot for placement."
websiteUrl = "https://github.com/doombubbles/AutoNudge"

[package.dependencies]
LavaGang-MelonLoader = "0.7.3"
doombubbles-Btd6ModHelper = "3.6.5"

[build]
icon = "./Icon.png"
readme = "./README.md"
outdir = "bin"

[[build.copy]]
source = "./bin/Release/AutoNudge.dll"
target = "AutoNudge.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = ["bloons-td-6"]
categories = ["mods"]
